services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-server
    command: pnpm run start:auth
    ports:
      - "5001:5001"
    env_file: .env
    depends_on:
      - mongo

  event-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-server
    command: pnpm run start:event
    ports:
      - "5003:5003"
    env_file: .env
    depends_on:
      - mongo

  gateway-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-server
    command: pnpm run start:gateway
    ports:
      - "5002:5002"
    env_file: .env
    depends_on:
      - auth-server
      - event-server

volumes:
  mongo-data:
